# Generated by Django 5.0.1 on 2024-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
