# Generated by Django 5.0.1 on 2024-04-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_farmer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='farmer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.disease'),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
