# Generated by Django 5.0.1 on 2024-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_farmer_alter_case_farmer1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='geom',
        ),
        migrations.AddField(
            model_name='case',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
