# Generated by Django 5.0.1 on 2024-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_case_geom_case_lat_case_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
