# Generated by Django 5.0.1 on 2024-04-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_case_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
