# Generated by Django 5.0.1 on 2024-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='case',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='backend.symptom'),
        ),
    ]
