# Generated by Django 5.0.1 on 2024-04-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_case_symptoms_case_symptoms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
