# Generated by Django 5.0.1 on 2024-04-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
