# Generated by Django 5.0.1 on 2024-04-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='district1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.district'),
        ),
    ]
