# Generated by Django 5.0.1 on 2024-04-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ward_district1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vet_officer',
        ),
    ]
