# Generated by Django 5.0.1 on 2024-04-29 20:01

from django.db import migrations

def populate_district_foreign(apps, schema_editor):
    Ward = apps.get_model('backend', 'Ward')
    District = apps.get_model('backend', 'District')

    for ward in Ward.objects.all():
        district_name = ward.district
        districts = District.objects.filter(name_2=district_name)
        if districts.exists():
            district = districts.first()
            ward.district_foreign = district
            ward.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_district1_ward_district_foreign_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_district_foreign),
    ]
