# Generated by Django 5.0.1 on 2024-04-29 20:34

from django.db import migrations

def populate_district_foreign_for_urban(apps, schema_editor):
    Ward = apps.get_model('backend', 'Ward')
    District = apps.get_model('backend', 'District')

    for ward in Ward.objects.filter(district__endswith='urban'):
        district_name = ward.district.lstrip('urban').strip()
        districts = District.objects.filter(name_2=district_name)
        if districts.exists():
            district = districts.first()
            ward.district_foreign = district
            ward.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20240429_2201'),
    ]

    operations = [
        migrations.RunPython(populate_district_foreign_for_urban),
    ]
