# Generated by Django 5.0.1 on 2024-04-29 21:59

from django.db import migrations

def populate_district_foreign(apps, schema_editor):
    Ward = apps.get_model('backend', 'Ward')
    District = apps.get_model('backend', 'District')

    chitungwiza_ward = Ward.objects.filter(district='Chitungwiza')
    harare_district = District.objects.get(name_2='Harare')

    for ward in chitungwiza_ward:
        ward.district_foreign = harare_district
        ward.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20240429_2241'),
    ]

    operations = [
        migrations.RunPython(populate_district_foreign),
    ]
