# Generated by Django 5.0.1 on 2024-04-29 22:27

from django.db import migrations

def populate_district_foreign(apps, schema_editor):
    Ward = apps.get_model('backend', 'Ward')
    District = apps.get_model('backend', 'District')

    epworth_ward = Ward.objects.filter(district='Epworth')
    norton_ward = Ward.objects.filter(district='Norton')
    chegutu_ward = Ward.objects.filter(district='Chegutu Urban')
    chinhoyi_ward = Ward.objects.filter(district='Chinhoyi')
    ruwa_ward = Ward.objects.filter(district='Ruwa')
    
    
    
    harare_district = District.objects.get(name_2='Harare')
    chegutu_district = District.objects.get(name_2='Chegutu')
    makonde_district = District.objects.get(name_2='Makonde')
    goromonzi_district = District.objects.get(name_2='Goromonzi')

    for ward in epworth_ward:
        ward.district_foreign = harare_district
        ward.save()
        
    for ward in norton_ward or  chegutu_ward:
        ward.district_foreign = chegutu_district
        ward.save()
        
    for ward in chinhoyi_ward:
        ward.district_foreign = makonde_district
        ward.save()
        
    for ward in ruwa_ward:
        ward.district_foreign = goromonzi_district
        ward.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20240429_2359'),
    ]

    operations = [
    ]
