# Generated by Django 5.0.1 on 2024-04-30 18:25

from django.db import migrations

def populate_district_foreign(apps, schema_editor):
    Ward = apps.get_model('backend', 'Ward')
    District = apps.get_model('backend', 'District')

    centenary_ward = Ward.objects.filter(district='Centenary/ Muzarabani')

    
    centenary_district = District.objects.get(name_2='Centenary')




        
    for ward in centenary_ward:
        ward.district_foreign = centenary_district
        ward.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20240430_0107'),
    ]

    operations = [
        migrations.RunPython(populate_district_foreign),
    ]
