# Generated by Django 5.0.1 on 2024-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_case_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='ndebele_description',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='ndebele_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='shona_description',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='shona_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
