# Generated by Django 5.0.1 on 2024-05-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_symptom_ndebele_description_symptom_ndebele_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='file',
            new_name='phone',
        ),
    ]
