# Generated by Django 5.0.1 on 2024-04-08 13:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('objectid_1', models.FloatField(null=True)),
                ('admin3name', models.CharField(max_length=254, null=True)),
                ('admin3pcod', models.CharField(max_length=254, null=True)),
                ('admin2name', models.CharField(max_length=254, null=True)),
                ('admin2pcod', models.CharField(max_length=254, null=True)),
                ('admin1name', models.CharField(max_length=254, null=True)),
                ('admin1pcod', models.CharField(max_length=254, null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('case_recor', models.CharField(max_length=254, null=True)),
                ('num_of_cas', models.CharField(max_length=254, null=True)),
                ('hotspot', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Spece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('Description', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('objectid_1', models.FloatField(null=True)),
                ('ward_name', models.CharField(max_length=254, null=True)),
                ('admin3pcod', models.CharField(max_length=254, null=True)),
                ('district', models.CharField(max_length=254, null=True)),
                ('admin2pcod', models.CharField(max_length=254, null=True)),
                ('province', models.CharField(max_length=254, null=True)),
                ('admin1pcod', models.CharField(max_length=254, null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('case_recor', models.CharField(max_length=254, null=True)),
                ('num_of_cas', models.CharField(max_length=254, null=True)),
                ('hotspot', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Animalcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.BigIntegerField(null=True)),
                ('spicies', models.CharField(max_length=254, null=True)),
                ('symptoms', models.CharField(max_length=254, null=True)),
                ('date', models.CharField(max_length=24, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('farmer3', models.CharField(max_length=254, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.district')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.district')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species_owned', models.ManyToManyField(blank=True, to='backend.spece')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
                ('affected_part', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='symptoms/images')),
                ('general_description', models.CharField(blank=True, max_length=254, null=True)),
                ('veterinarian_description', models.CharField(blank=True, max_length=254, null=True)),
                ('spece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.spece')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('vector_associated', models.CharField(blank=True, max_length=75, null=True)),
                ('spece_affected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.spece')),
                ('symptoms', models.ManyToManyField(blank=True, to='backend.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.district')),
                ('farmer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.farmer')),
                ('spece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.spece')),
                ('symptoms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.symptom')),
            ],
        ),
    ]
