# Generated by Django 5.0.1 on 2024-04-06 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='id',
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom_id',
            field=models.BigAutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
