# Generated by Django 5.0.1 on 2024-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_symptom_id_symptom_symptom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='symptom_id',
        ),
        migrations.AddField(
            model_name='symptom',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
